namespace FNFBot20
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.pnlSidebar = new System.Windows.Forms.Panel();
            this.lblSidebarFooter = new System.Windows.Forms.Label();
            this.navIndicator = new System.Windows.Forms.Panel();
            this.navKeybinds = new FNFBot20.AnimatedButton();
            this.navDashboard = new FNFBot20.AnimatedButton();
            this.lblBrandSubtitle = new System.Windows.Forms.Label();
            this.pnlLogo = new System.Windows.Forms.Panel();
            this.pnlMain = new System.Windows.Forms.Panel();
            this.pnlPageHost = new System.Windows.Forms.Panel();
            this.pnlKeybindPage = new FNFBot20.DoubleBufferedPanel();
            this.pnlLaneBindings = new FNFBot20.RoundedPanel();
            this.flpLaneKeys = new System.Windows.Forms.FlowLayoutPanel();
            this.btnResetAllLaneKeys = new FNFBot20.AnimatedButton();
            this.btnResetLaneKeys = new FNFBot20.AnimatedButton();
            this.cmbLaneCount = new System.Windows.Forms.ComboBox();
            this.lblDetectedLayout = new System.Windows.Forms.Label();
            this.lblLaneProfile = new System.Windows.Forms.Label();
            this.pnlControlBindings = new FNFBot20.RoundedPanel();
            this.btnResetShortcuts = new FNFBot20.AnimatedButton();
            this.btnBindOffsetDown = new FNFBot20.AnimatedButton();
            this.btnBindOffsetUp = new FNFBot20.AnimatedButton();
            this.btnBindPlay = new FNFBot20.AnimatedButton();
            this.lblOffsetDownKey = new System.Windows.Forms.Label();
            this.lblOffsetUpKey = new System.Windows.Forms.Label();
            this.lblPlayKey = new System.Windows.Forms.Label();
            this.lblOffsetDownName = new System.Windows.Forms.Label();
            this.lblOffsetUpName = new System.Windows.Forms.Label();
            this.lblPlayName = new System.Windows.Forms.Label();
            this.lblControlBindingsTitle = new System.Windows.Forms.Label();
            this.lblKeybindSubtitle = new System.Windows.Forms.Label();
            this.lblKeybindTitle = new System.Windows.Forms.Label();
            this.pnlDashboardPage = new FNFBot20.DoubleBufferedPanel();
            this.pnlLibraryCard = new FNFBot20.RoundedPanel();
            this.treSngSelect = new System.Windows.Forms.TreeView();
            this.lblLibraryTitle = new System.Windows.Forms.Label();
            this.pnlConsoleCard = new FNFBot20.RoundedPanel();
            this.rchConsole = new System.Windows.Forms.RichTextBox();
            this.lblConsoleTitle = new System.Windows.Forms.Label();
            this.pnlPreviewCard = new FNFBot20.RoundedPanel();
            this.pnlPlayField = new System.Windows.Forms.Panel();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.lblPreviewTitle = new System.Windows.Forms.Label();
            this.pnlPathCard = new FNFBot20.RoundedPanel();
            this.btnManual = new FNFBot20.AnimatedButton();
            this.button2 = new FNFBot20.AnimatedButton();
            this.txtbxDir = new System.Windows.Forms.TextBox();
            this.lblPathTitle = new System.Windows.Forms.Label();
            this.pnlTop = new System.Windows.Forms.Panel();
            this.button1 = new FNFBot20.AnimatedButton();
            this.btnMinimize = new FNFBot20.AnimatedButton();
            this.btnResetOffset = new FNFBot20.AnimatedButton();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.lblVer = new System.Windows.Forms.Label();
            this.navAnimationTimer = new System.Windows.Forms.Timer(this.components);
            this.pnlSidebar.SuspendLayout();
            this.pnlMain.SuspendLayout();
            this.pnlPageHost.SuspendLayout();
            this.pnlKeybindPage.SuspendLayout();
            this.pnlLaneBindings.SuspendLayout();
            this.pnlControlBindings.SuspendLayout();
            this.pnlDashboardPage.SuspendLayout();
            this.pnlLibraryCard.SuspendLayout();
            this.pnlConsoleCard.SuspendLayout();
            this.pnlPreviewCard.SuspendLayout();
            this.pnlPathCard.SuspendLayout();
            this.pnlTop.SuspendLayout();
            this.SuspendLayout();
            this.pnlSidebar.BackColor = System.Drawing.Color.FromArgb(13, 10, 23);
            this.pnlSidebar.Controls.Add(this.lblSidebarFooter);
            this.pnlSidebar.Controls.Add(this.navIndicator);
            this.pnlSidebar.Controls.Add(this.navKeybinds);
            this.pnlSidebar.Controls.Add(this.navDashboard);
            this.pnlSidebar.Controls.Add(this.lblBrandSubtitle);
            this.pnlSidebar.Controls.Add(this.pnlLogo);
            this.pnlSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlSidebar.Location = new System.Drawing.Point(0, 0);
            this.pnlSidebar.Name = "pnlSidebar";
            this.pnlSidebar.Size = new System.Drawing.Size(180, 680);
            this.pnlSidebar.TabIndex = 0;
            this.lblSidebarFooter.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.lblSidebarFooter.AutoSize = true;
            this.lblSidebarFooter.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.lblSidebarFooter.ForeColor = System.Drawing.Color.FromArgb(104, 94, 125);
            this.lblSidebarFooter.Location = new System.Drawing.Point(22, 645);
            this.lblSidebarFooter.Name = "lblSidebarFooter";
            this.lblSidebarFooter.Size = new System.Drawing.Size(96, 13);
            this.lblSidebarFooter.TabIndex = 5;
            this.lblSidebarFooter.Text = "FNFBot • Reworked";
            this.navIndicator.BackColor = System.Drawing.Color.FromArgb(139, 92, 246);
            this.navIndicator.Location = new System.Drawing.Point(0, 112);
            this.navIndicator.Name = "navIndicator";
            this.navIndicator.Size = new System.Drawing.Size(4, 42);
            this.navIndicator.TabIndex = 4;
            this.navKeybinds.CornerRadius = 8;
            this.navKeybinds.FlatAppearance.BorderSize = 0;
            this.navKeybinds.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.navKeybinds.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.navKeybinds.ForeColor = System.Drawing.Color.FromArgb(218, 211, 232);
            this.navKeybinds.HoverColor = System.Drawing.Color.FromArgb(50, 38, 77);
            this.navKeybinds.Location = new System.Drawing.Point(14, 164);
            this.navKeybinds.Name = "navKeybinds";
            this.navKeybinds.NormalColor = System.Drawing.Color.FromArgb(24, 18, 41);
            this.navKeybinds.PressedColor = System.Drawing.Color.FromArgb(76, 53, 119);
            this.navKeybinds.Size = new System.Drawing.Size(152, 42);
            this.navKeybinds.TabIndex = 3;
            this.navKeybinds.Text = "Keybinds";
            this.navKeybinds.UseVisualStyleBackColor = false;
            this.navKeybinds.Click += new System.EventHandler(this.navKeybinds_Click);
            this.navDashboard.CornerRadius = 8;
            this.navDashboard.FlatAppearance.BorderSize = 0;
            this.navDashboard.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.navDashboard.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.navDashboard.ForeColor = System.Drawing.Color.FromArgb(239, 235, 250);
            this.navDashboard.HoverColor = System.Drawing.Color.FromArgb(50, 38, 77);
            this.navDashboard.Location = new System.Drawing.Point(14, 112);
            this.navDashboard.Name = "navDashboard";
            this.navDashboard.NormalColor = System.Drawing.Color.FromArgb(49, 35, 78);
            this.navDashboard.PressedColor = System.Drawing.Color.FromArgb(76, 53, 119);
            this.navDashboard.Size = new System.Drawing.Size(152, 42);
            this.navDashboard.TabIndex = 2;
            this.navDashboard.Text = "Dashboard";
            this.navDashboard.UseVisualStyleBackColor = false;
            this.navDashboard.Click += new System.EventHandler(this.navDashboard_Click);
            this.lblBrandSubtitle.AutoSize = true;
            this.lblBrandSubtitle.Font = new System.Drawing.Font("Segoe UI Semibold", 8F);
            this.lblBrandSubtitle.ForeColor = System.Drawing.Color.FromArgb(139, 92, 246);
            this.lblBrandSubtitle.Location = new System.Drawing.Point(22, 73);
            this.lblBrandSubtitle.Name = "lblBrandSubtitle";
            this.lblBrandSubtitle.Size = new System.Drawing.Size(98, 13);
            this.lblBrandSubtitle.TabIndex = 1;
            this.lblBrandSubtitle.Text = "MIDNIGHT EDITION";
            this.pnlLogo.BackgroundImage = global::FNFBot20.Properties.Resources.FNFBotLogo;
            this.pnlLogo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.pnlLogo.Location = new System.Drawing.Point(20, 22);
            this.pnlLogo.Name = "pnlLogo";
            this.pnlLogo.Size = new System.Drawing.Size(132, 38);
            this.pnlLogo.TabIndex = 0;
            this.pnlMain.BackColor = System.Drawing.Color.FromArgb(16, 12, 28);
            this.pnlMain.Controls.Add(this.pnlPageHost);
            this.pnlMain.Controls.Add(this.pnlTop);
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(180, 0);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Size = new System.Drawing.Size(860, 680);
            this.pnlMain.TabIndex = 1;
            this.pnlPageHost.Controls.Add(this.pnlKeybindPage);
            this.pnlPageHost.Controls.Add(this.pnlDashboardPage);
            this.pnlPageHost.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlPageHost.Location = new System.Drawing.Point(0, 56);
            this.pnlPageHost.Name = "pnlPageHost";
            this.pnlPageHost.Size = new System.Drawing.Size(860, 624);
            this.pnlPageHost.TabIndex = 1;
            this.pnlKeybindPage.BackColor = System.Drawing.Color.FromArgb(16, 12, 28);
            this.pnlKeybindPage.Controls.Add(this.pnlLaneBindings);
            this.pnlKeybindPage.Controls.Add(this.pnlControlBindings);
            this.pnlKeybindPage.Controls.Add(this.lblKeybindSubtitle);
            this.pnlKeybindPage.Controls.Add(this.lblKeybindTitle);
            this.pnlKeybindPage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlKeybindPage.Location = new System.Drawing.Point(0, 0);
            this.pnlKeybindPage.Name = "pnlKeybindPage";
            this.pnlKeybindPage.Padding = new System.Windows.Forms.Padding(20);
            this.pnlKeybindPage.Size = new System.Drawing.Size(860, 624);
            this.pnlKeybindPage.TabIndex = 1;
            this.pnlLaneBindings.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlLaneBindings.BackColor = System.Drawing.Color.FromArgb(27, 21, 46);
            this.pnlLaneBindings.BorderColor = System.Drawing.Color.FromArgb(44, 35, 65);
            this.pnlLaneBindings.BorderThickness = 1;
            this.pnlLaneBindings.Controls.Add(this.flpLaneKeys);
            this.pnlLaneBindings.Controls.Add(this.btnResetAllLaneKeys);
            this.pnlLaneBindings.Controls.Add(this.btnResetLaneKeys);
            this.pnlLaneBindings.Controls.Add(this.cmbLaneCount);
            this.pnlLaneBindings.Controls.Add(this.lblDetectedLayout);
            this.pnlLaneBindings.Controls.Add(this.lblLaneProfile);
            this.pnlLaneBindings.CornerRadius = 12;
            this.pnlLaneBindings.Location = new System.Drawing.Point(20, 244);
            this.pnlLaneBindings.Name = "pnlLaneBindings";
            this.pnlLaneBindings.Size = new System.Drawing.Size(820, 360);
            this.pnlLaneBindings.TabIndex = 3;
            this.flpLaneKeys.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.flpLaneKeys.AutoScroll = true;
            this.flpLaneKeys.BackColor = System.Drawing.Color.FromArgb(22, 17, 38);
            this.flpLaneKeys.Location = new System.Drawing.Point(18, 84);
            this.flpLaneKeys.Name = "flpLaneKeys";
            this.flpLaneKeys.Padding = new System.Windows.Forms.Padding(10);
            this.flpLaneKeys.Size = new System.Drawing.Size(784, 258);
            this.flpLaneKeys.TabIndex = 5;
            this.btnResetAllLaneKeys.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnResetAllLaneKeys.CornerRadius = 8;
            this.btnResetAllLaneKeys.FlatAppearance.BorderSize = 0;
            this.btnResetAllLaneKeys.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnResetAllLaneKeys.Font = new System.Drawing.Font("Segoe UI Semibold", 9F);
            this.btnResetAllLaneKeys.ForeColor = System.Drawing.Color.FromArgb(222, 214, 239);
            this.btnResetAllLaneKeys.HoverColor = System.Drawing.Color.FromArgb(65, 48, 100);
            this.btnResetAllLaneKeys.Location = new System.Drawing.Point(665, 22);
            this.btnResetAllLaneKeys.Name = "btnResetAllLaneKeys";
            this.btnResetAllLaneKeys.NormalColor = System.Drawing.Color.FromArgb(36, 28, 58);
            this.btnResetAllLaneKeys.PressedColor = System.Drawing.Color.FromArgb(86, 61, 135);
            this.btnResetAllLaneKeys.Size = new System.Drawing.Size(137, 36);
            this.btnResetAllLaneKeys.TabIndex = 4;
            this.btnResetAllLaneKeys.Text = "Reset all profiles";
            this.btnResetAllLaneKeys.UseVisualStyleBackColor = false;
            this.btnResetAllLaneKeys.Click += new System.EventHandler(this.btnResetAllLaneKeys_Click);
            this.btnResetLaneKeys.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnResetLaneKeys.CornerRadius = 8;
            this.btnResetLaneKeys.FlatAppearance.BorderSize = 0;
            this.btnResetLaneKeys.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnResetLaneKeys.Font = new System.Drawing.Font("Segoe UI Semibold", 9F);
            this.btnResetLaneKeys.ForeColor = System.Drawing.Color.FromArgb(222, 214, 239);
            this.btnResetLaneKeys.HoverColor = System.Drawing.Color.FromArgb(65, 48, 100);
            this.btnResetLaneKeys.Location = new System.Drawing.Point(530, 22);
            this.btnResetLaneKeys.Name = "btnResetLaneKeys";
            this.btnResetLaneKeys.NormalColor = System.Drawing.Color.FromArgb(36, 28, 58);
            this.btnResetLaneKeys.PressedColor = System.Drawing.Color.FromArgb(86, 61, 135);
            this.btnResetLaneKeys.Size = new System.Drawing.Size(125, 36);
            this.btnResetLaneKeys.TabIndex = 3;
            this.btnResetLaneKeys.Text = "Reset current";
            this.btnResetLaneKeys.UseVisualStyleBackColor = false;
            this.btnResetLaneKeys.Click += new System.EventHandler(this.btnResetLaneKeys_Click);
            this.cmbLaneCount.BackColor = System.Drawing.Color.FromArgb(36, 28, 58);
            this.cmbLaneCount.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbLaneCount.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbLaneCount.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.cmbLaneCount.ForeColor = System.Drawing.Color.White;
            this.cmbLaneCount.FormattingEnabled = true;
            this.cmbLaneCount.Location = new System.Drawing.Point(244, 30);
            this.cmbLaneCount.Name = "cmbLaneCount";
            this.cmbLaneCount.Size = new System.Drawing.Size(82, 25);
            this.cmbLaneCount.TabIndex = 2;
            this.cmbLaneCount.SelectedIndexChanged += new System.EventHandler(this.cmbLaneCount_SelectedIndexChanged);
            this.lblDetectedLayout.AutoSize = true;
            this.lblDetectedLayout.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblDetectedLayout.ForeColor = System.Drawing.Color.FromArgb(132, 119, 154);
            this.lblDetectedLayout.Location = new System.Drawing.Point(18, 50);
            this.lblDetectedLayout.Name = "lblDetectedLayout";
            this.lblDetectedLayout.Size = new System.Drawing.Size(110, 15);
            this.lblDetectedLayout.TabIndex = 1;
            this.lblDetectedLayout.Text = "Detected layout: 4K";
            this.lblLaneProfile.AutoSize = true;
            this.lblLaneProfile.Font = new System.Drawing.Font("Segoe UI Semibold", 12F);
            this.lblLaneProfile.ForeColor = System.Drawing.Color.FromArgb(241, 237, 249);
            this.lblLaneProfile.Location = new System.Drawing.Point(18, 22);
            this.lblLaneProfile.Name = "lblLaneProfile";
            this.lblLaneProfile.Size = new System.Drawing.Size(112, 21);
            this.lblLaneProfile.TabIndex = 0;
            this.lblLaneProfile.Text = "4K key profile";
            this.pnlControlBindings.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlControlBindings.BackColor = System.Drawing.Color.FromArgb(27, 21, 46);
            this.pnlControlBindings.BorderColor = System.Drawing.Color.FromArgb(44, 35, 65);
            this.pnlControlBindings.BorderThickness = 1;
            this.pnlControlBindings.Controls.Add(this.btnResetShortcuts);
            this.pnlControlBindings.Controls.Add(this.btnBindOffsetDown);
            this.pnlControlBindings.Controls.Add(this.btnBindOffsetUp);
            this.pnlControlBindings.Controls.Add(this.btnBindPlay);
            this.pnlControlBindings.Controls.Add(this.lblOffsetDownKey);
            this.pnlControlBindings.Controls.Add(this.lblOffsetUpKey);
            this.pnlControlBindings.Controls.Add(this.lblPlayKey);
            this.pnlControlBindings.Controls.Add(this.lblOffsetDownName);
            this.pnlControlBindings.Controls.Add(this.lblOffsetUpName);
            this.pnlControlBindings.Controls.Add(this.lblPlayName);
            this.pnlControlBindings.Controls.Add(this.lblControlBindingsTitle);
            this.pnlControlBindings.CornerRadius = 12;
            this.pnlControlBindings.Location = new System.Drawing.Point(20, 72);
            this.pnlControlBindings.Name = "pnlControlBindings";
            this.pnlControlBindings.Size = new System.Drawing.Size(820, 154);
            this.pnlControlBindings.TabIndex = 2;
            this.btnResetShortcuts.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnResetShortcuts.CornerRadius = 7;
            this.btnResetShortcuts.FlatAppearance.BorderSize = 0;
            this.btnResetShortcuts.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnResetShortcuts.Font = new System.Drawing.Font("Segoe UI Semibold", 8F);
            this.btnResetShortcuts.ForeColor = System.Drawing.Color.FromArgb(194, 181, 217);
            this.btnResetShortcuts.HoverColor = System.Drawing.Color.FromArgb(65, 48, 100);
            this.btnResetShortcuts.Location = new System.Drawing.Point(683, 8);
            this.btnResetShortcuts.Name = "btnResetShortcuts";
            this.btnResetShortcuts.NormalColor = System.Drawing.Color.FromArgb(36, 28, 58);
            this.btnResetShortcuts.PressedColor = System.Drawing.Color.FromArgb(86, 61, 135);
            this.btnResetShortcuts.Size = new System.Drawing.Size(119, 24);
            this.btnResetShortcuts.TabIndex = 10;
            this.btnResetShortcuts.Text = "Reset shortcuts";
            this.btnResetShortcuts.UseVisualStyleBackColor = false;
            this.btnResetShortcuts.Click += new System.EventHandler(this.btnResetShortcuts_Click);
            this.btnBindOffsetDown.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBindOffsetDown.CornerRadius = 7;
            this.btnBindOffsetDown.FlatAppearance.BorderSize = 0;
            this.btnBindOffsetDown.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBindOffsetDown.Font = new System.Drawing.Font("Segoe UI Semibold", 8.5F);
            this.btnBindOffsetDown.ForeColor = System.Drawing.Color.White;
            this.btnBindOffsetDown.HoverColor = System.Drawing.Color.FromArgb(76, 54, 116);
            this.btnBindOffsetDown.Location = new System.Drawing.Point(700, 108);
            this.btnBindOffsetDown.Name = "btnBindOffsetDown";
            this.btnBindOffsetDown.NormalColor = System.Drawing.Color.FromArgb(58, 41, 90);
            this.btnBindOffsetDown.PressedColor = System.Drawing.Color.FromArgb(101, 68, 157);
            this.btnBindOffsetDown.Size = new System.Drawing.Size(102, 30);
            this.btnBindOffsetDown.TabIndex = 9;
            this.btnBindOffsetDown.Text = "Change";
            this.btnBindOffsetDown.UseVisualStyleBackColor = false;
            this.btnBindOffsetDown.Click += new System.EventHandler(this.btnBindOffsetDown_Click);
            this.btnBindOffsetUp.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBindOffsetUp.CornerRadius = 7;
            this.btnBindOffsetUp.FlatAppearance.BorderSize = 0;
            this.btnBindOffsetUp.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBindOffsetUp.Font = new System.Drawing.Font("Segoe UI Semibold", 8.5F);
            this.btnBindOffsetUp.ForeColor = System.Drawing.Color.White;
            this.btnBindOffsetUp.HoverColor = System.Drawing.Color.FromArgb(76, 54, 116);
            this.btnBindOffsetUp.Location = new System.Drawing.Point(700, 72);
            this.btnBindOffsetUp.Name = "btnBindOffsetUp";
            this.btnBindOffsetUp.NormalColor = System.Drawing.Color.FromArgb(58, 41, 90);
            this.btnBindOffsetUp.PressedColor = System.Drawing.Color.FromArgb(101, 68, 157);
            this.btnBindOffsetUp.Size = new System.Drawing.Size(102, 30);
            this.btnBindOffsetUp.TabIndex = 8;
            this.btnBindOffsetUp.Text = "Change";
            this.btnBindOffsetUp.UseVisualStyleBackColor = false;
            this.btnBindOffsetUp.Click += new System.EventHandler(this.btnBindOffsetUp_Click);
            this.btnBindPlay.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBindPlay.CornerRadius = 7;
            this.btnBindPlay.FlatAppearance.BorderSize = 0;
            this.btnBindPlay.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBindPlay.Font = new System.Drawing.Font("Segoe UI Semibold", 8.5F);
            this.btnBindPlay.ForeColor = System.Drawing.Color.White;
            this.btnBindPlay.HoverColor = System.Drawing.Color.FromArgb(76, 54, 116);
            this.btnBindPlay.Location = new System.Drawing.Point(700, 36);
            this.btnBindPlay.Name = "btnBindPlay";
            this.btnBindPlay.NormalColor = System.Drawing.Color.FromArgb(58, 41, 90);
            this.btnBindPlay.PressedColor = System.Drawing.Color.FromArgb(101, 68, 157);
            this.btnBindPlay.Size = new System.Drawing.Size(102, 30);
            this.btnBindPlay.TabIndex = 7;
            this.btnBindPlay.Text = "Change";
            this.btnBindPlay.UseVisualStyleBackColor = false;
            this.btnBindPlay.Click += new System.EventHandler(this.btnBindPlay_Click);
            this.lblOffsetDownKey.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lblOffsetDownKey.Font = new System.Drawing.Font("Segoe UI Semibold", 9F);
            this.lblOffsetDownKey.ForeColor = System.Drawing.Color.FromArgb(179, 159, 218);
            this.lblOffsetDownKey.Location = new System.Drawing.Point(530, 113);
            this.lblOffsetDownKey.Name = "lblOffsetDownKey";
            this.lblOffsetDownKey.Size = new System.Drawing.Size(156, 20);
            this.lblOffsetDownKey.TabIndex = 6;
            this.lblOffsetDownKey.Text = "F3";
            this.lblOffsetDownKey.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblOffsetUpKey.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lblOffsetUpKey.Font = new System.Drawing.Font("Segoe UI Semibold", 9F);
            this.lblOffsetUpKey.ForeColor = System.Drawing.Color.FromArgb(179, 159, 218);
            this.lblOffsetUpKey.Location = new System.Drawing.Point(530, 77);
            this.lblOffsetUpKey.Name = "lblOffsetUpKey";
            this.lblOffsetUpKey.Size = new System.Drawing.Size(156, 20);
            this.lblOffsetUpKey.TabIndex = 5;
            this.lblOffsetUpKey.Text = "F2";
            this.lblOffsetUpKey.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblPlayKey.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lblPlayKey.Font = new System.Drawing.Font("Segoe UI Semibold", 9F);
            this.lblPlayKey.ForeColor = System.Drawing.Color.FromArgb(179, 159, 218);
            this.lblPlayKey.Location = new System.Drawing.Point(530, 41);
            this.lblPlayKey.Name = "lblPlayKey";
            this.lblPlayKey.Size = new System.Drawing.Size(156, 20);
            this.lblPlayKey.TabIndex = 4;
            this.lblPlayKey.Text = "F1";
            this.lblPlayKey.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblOffsetDownName.AutoSize = true;
            this.lblOffsetDownName.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblOffsetDownName.ForeColor = System.Drawing.Color.FromArgb(209, 202, 222);
            this.lblOffsetDownName.Location = new System.Drawing.Point(18, 114);
            this.lblOffsetDownName.Name = "lblOffsetDownName";
            this.lblOffsetDownName.Size = new System.Drawing.Size(135, 15);
            this.lblOffsetDownName.TabIndex = 3;
            this.lblOffsetDownName.Text = "Decrease playback offset";
            this.lblOffsetUpName.AutoSize = true;
            this.lblOffsetUpName.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblOffsetUpName.ForeColor = System.Drawing.Color.FromArgb(209, 202, 222);
            this.lblOffsetUpName.Location = new System.Drawing.Point(18, 78);
            this.lblOffsetUpName.Name = "lblOffsetUpName";
            this.lblOffsetUpName.Size = new System.Drawing.Size(130, 15);
            this.lblOffsetUpName.TabIndex = 2;
            this.lblOffsetUpName.Text = "Increase playback offset";
            this.lblPlayName.AutoSize = true;
            this.lblPlayName.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblPlayName.ForeColor = System.Drawing.Color.FromArgb(209, 202, 222);
            this.lblPlayName.Location = new System.Drawing.Point(18, 42);
            this.lblPlayName.Name = "lblPlayName";
            this.lblPlayName.Size = new System.Drawing.Size(108, 15);
            this.lblPlayName.TabIndex = 1;
            this.lblPlayName.Text = "Start / stop autoplay";
            this.lblControlBindingsTitle.AutoSize = true;
            this.lblControlBindingsTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.lblControlBindingsTitle.ForeColor = System.Drawing.Color.FromArgb(241, 237, 249);
            this.lblControlBindingsTitle.Location = new System.Drawing.Point(18, 12);
            this.lblControlBindingsTitle.Name = "lblControlBindingsTitle";
            this.lblControlBindingsTitle.Size = new System.Drawing.Size(112, 20);
            this.lblControlBindingsTitle.TabIndex = 0;
            this.lblControlBindingsTitle.Text = "Bot shortcuts";
            this.lblKeybindSubtitle.AutoSize = true;
            this.lblKeybindSubtitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblKeybindSubtitle.ForeColor = System.Drawing.Color.FromArgb(130, 118, 151);
            this.lblKeybindSubtitle.Location = new System.Drawing.Point(22, 48);
            this.lblKeybindSubtitle.Name = "lblKeybindSubtitle";
            this.lblKeybindSubtitle.Size = new System.Drawing.Size(378, 15);
            this.lblKeybindSubtitle.TabIndex = 1;
            this.lblKeybindSubtitle.Text = "Customize shortcuts and keep separate lane profiles for every key mode.";
            this.lblKeybindTitle.AutoSize = true;
            this.lblKeybindTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 18F);
            this.lblKeybindTitle.ForeColor = System.Drawing.Color.FromArgb(245, 242, 250);
            this.lblKeybindTitle.Location = new System.Drawing.Point(18, 13);
            this.lblKeybindTitle.Name = "lblKeybindTitle";
            this.lblKeybindTitle.Size = new System.Drawing.Size(110, 32);
            this.lblKeybindTitle.TabIndex = 0;
            this.lblKeybindTitle.Text = "Keybinds";
            this.pnlDashboardPage.BackColor = System.Drawing.Color.FromArgb(16, 12, 28);
            this.pnlDashboardPage.Controls.Add(this.pnlLibraryCard);
            this.pnlDashboardPage.Controls.Add(this.pnlConsoleCard);
            this.pnlDashboardPage.Controls.Add(this.pnlPreviewCard);
            this.pnlDashboardPage.Controls.Add(this.pnlPathCard);
            this.pnlDashboardPage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDashboardPage.Location = new System.Drawing.Point(0, 0);
            this.pnlDashboardPage.Name = "pnlDashboardPage";
            this.pnlDashboardPage.Size = new System.Drawing.Size(860, 624);
            this.pnlDashboardPage.TabIndex = 0;
            this.pnlLibraryCard.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlLibraryCard.BackColor = System.Drawing.Color.FromArgb(27, 21, 46);
            this.pnlLibraryCard.BorderColor = System.Drawing.Color.FromArgb(44, 35, 65);
            this.pnlLibraryCard.BorderThickness = 1;
            this.pnlLibraryCard.Controls.Add(this.treSngSelect);
            this.pnlLibraryCard.Controls.Add(this.lblLibraryTitle);
            this.pnlLibraryCard.CornerRadius = 12;
            this.pnlLibraryCard.Location = new System.Drawing.Point(20, 399);
            this.pnlLibraryCard.Name = "pnlLibraryCard";
            this.pnlLibraryCard.Size = new System.Drawing.Size(820, 205);
            this.pnlLibraryCard.TabIndex = 3;
            this.treSngSelect.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.treSngSelect.BackColor = System.Drawing.Color.FromArgb(22, 17, 38);
            this.treSngSelect.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.treSngSelect.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.treSngSelect.ForeColor = System.Drawing.Color.FromArgb(226, 220, 238);
            this.treSngSelect.FullRowSelect = true;
            this.treSngSelect.HideSelection = false;
            this.treSngSelect.Location = new System.Drawing.Point(16, 43);
            this.treSngSelect.Name = "treSngSelect";
            this.treSngSelect.Size = new System.Drawing.Size(788, 146);
            this.treSngSelect.TabIndex = 1;
            this.treSngSelect.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.treSngSelect_NodeMouseDoubleClick);
            this.lblLibraryTitle.AutoSize = true;
            this.lblLibraryTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.lblLibraryTitle.ForeColor = System.Drawing.Color.FromArgb(240, 236, 248);
            this.lblLibraryTitle.Location = new System.Drawing.Point(16, 14);
            this.lblLibraryTitle.Name = "lblLibraryTitle";
            this.lblLibraryTitle.Size = new System.Drawing.Size(88, 20);
            this.lblLibraryTitle.TabIndex = 0;
            this.lblLibraryTitle.Text = "Song library";
            this.pnlConsoleCard.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlConsoleCard.BackColor = System.Drawing.Color.FromArgb(27, 21, 46);
            this.pnlConsoleCard.BorderColor = System.Drawing.Color.FromArgb(44, 35, 65);
            this.pnlConsoleCard.BorderThickness = 1;
            this.pnlConsoleCard.Controls.Add(this.rchConsole);
            this.pnlConsoleCard.Controls.Add(this.lblConsoleTitle);
            this.pnlConsoleCard.CornerRadius = 12;
            this.pnlConsoleCard.Location = new System.Drawing.Point(332, 103);
            this.pnlConsoleCard.Name = "pnlConsoleCard";
            this.pnlConsoleCard.Size = new System.Drawing.Size(508, 278);
            this.pnlConsoleCard.TabIndex = 2;
            this.rchConsole.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.rchConsole.BackColor = System.Drawing.Color.FromArgb(22, 17, 38);
            this.rchConsole.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.rchConsole.Font = new System.Drawing.Font("Consolas", 9F);
            this.rchConsole.ForeColor = System.Drawing.Color.FromArgb(213, 204, 229);
            this.rchConsole.Location = new System.Drawing.Point(16, 43);
            this.rchConsole.Name = "rchConsole";
            this.rchConsole.ReadOnly = true;
            this.rchConsole.Size = new System.Drawing.Size(476, 219);
            this.rchConsole.TabIndex = 1;
            this.rchConsole.Text = "";
            this.lblConsoleTitle.AutoSize = true;
            this.lblConsoleTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.lblConsoleTitle.ForeColor = System.Drawing.Color.FromArgb(240, 236, 248);
            this.lblConsoleTitle.Location = new System.Drawing.Point(16, 14);
            this.lblConsoleTitle.Name = "lblConsoleTitle";
            this.lblConsoleTitle.Size = new System.Drawing.Size(61, 20);
            this.lblConsoleTitle.TabIndex = 0;
            this.lblConsoleTitle.Text = "Activity";
            this.pnlPreviewCard.BackColor = System.Drawing.Color.FromArgb(27, 21, 46);
            this.pnlPreviewCard.BorderColor = System.Drawing.Color.FromArgb(44, 35, 65);
            this.pnlPreviewCard.BorderThickness = 1;
            this.pnlPreviewCard.Controls.Add(this.pnlPlayField);
            this.pnlPreviewCard.Controls.Add(this.checkBox1);
            this.pnlPreviewCard.Controls.Add(this.lblPreviewTitle);
            this.pnlPreviewCard.CornerRadius = 12;
            this.pnlPreviewCard.Location = new System.Drawing.Point(20, 103);
            this.pnlPreviewCard.Name = "pnlPreviewCard";
            this.pnlPreviewCard.Size = new System.Drawing.Size(296, 278);
            this.pnlPreviewCard.TabIndex = 1;
            this.pnlPlayField.BackColor = System.Drawing.Color.FromArgb(22, 17, 38);
            this.pnlPlayField.Location = new System.Drawing.Point(16, 47);
            this.pnlPlayField.Name = "pnlPlayField";
            this.pnlPlayField.Size = new System.Drawing.Size(264, 215);
            this.pnlPlayField.TabIndex = 2;
            this.checkBox1.AutoSize = true;
            this.checkBox1.Checked = true;
            this.checkBox1.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox1.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.checkBox1.ForeColor = System.Drawing.Color.FromArgb(161, 148, 181);
            this.checkBox1.Location = new System.Drawing.Point(190, 18);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(64, 17);
            this.checkBox1.TabIndex = 1;
            this.checkBox1.Text = "Render";
            this.checkBox1.UseVisualStyleBackColor = true;
            this.checkBox1.CheckedChanged += new System.EventHandler(this.checkBox1_CheckedChanged);
            this.lblPreviewTitle.AutoSize = true;
            this.lblPreviewTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.lblPreviewTitle.ForeColor = System.Drawing.Color.FromArgb(240, 236, 248);
            this.lblPreviewTitle.Location = new System.Drawing.Point(16, 14);
            this.lblPreviewTitle.Name = "lblPreviewTitle";
            this.lblPreviewTitle.Size = new System.Drawing.Size(97, 20);
            this.lblPreviewTitle.TabIndex = 0;
            this.lblPreviewTitle.Text = "Note preview";
            this.pnlPathCard.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlPathCard.BackColor = System.Drawing.Color.FromArgb(27, 21, 46);
            this.pnlPathCard.BorderColor = System.Drawing.Color.FromArgb(44, 35, 65);
            this.pnlPathCard.BorderThickness = 1;
            this.pnlPathCard.Controls.Add(this.btnManual);
            this.pnlPathCard.Controls.Add(this.button2);
            this.pnlPathCard.Controls.Add(this.txtbxDir);
            this.pnlPathCard.Controls.Add(this.lblPathTitle);
            this.pnlPathCard.CornerRadius = 12;
            this.pnlPathCard.Location = new System.Drawing.Point(20, 18);
            this.pnlPathCard.Name = "pnlPathCard";
            this.pnlPathCard.Size = new System.Drawing.Size(820, 68);
            this.pnlPathCard.TabIndex = 0;
            this.btnManual.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnManual.CornerRadius = 7;
            this.btnManual.FlatAppearance.BorderSize = 0;
            this.btnManual.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnManual.Font = new System.Drawing.Font("Segoe UI Semibold", 8.5F);
            this.btnManual.ForeColor = System.Drawing.Color.White;
            this.btnManual.HoverColor = System.Drawing.Color.FromArgb(74, 51, 116);
            this.btnManual.Location = new System.Drawing.Point(700, 26);
            this.btnManual.Name = "btnManual";
            this.btnManual.NormalColor = System.Drawing.Color.FromArgb(55, 39, 86);
            this.btnManual.PressedColor = System.Drawing.Color.FromArgb(101, 68, 157);
            this.btnManual.Size = new System.Drawing.Size(102, 30);
            this.btnManual.TabIndex = 3;
            this.btnManual.Text = "Open chart";
            this.btnManual.UseVisualStyleBackColor = false;
            this.btnManual.Click += new System.EventHandler(this.btnManual_Click);
            this.button2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.button2.CornerRadius = 7;
            this.button2.FlatAppearance.BorderSize = 0;
            this.button2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button2.Font = new System.Drawing.Font("Segoe UI Semibold", 8.5F);
            this.button2.ForeColor = System.Drawing.Color.White;
            this.button2.HoverColor = System.Drawing.Color.FromArgb(97, 64, 154);
            this.button2.Location = new System.Drawing.Point(588, 26);
            this.button2.Name = "button2";
            this.button2.NormalColor = System.Drawing.Color.FromArgb(74, 49, 116);
            this.button2.PressedColor = System.Drawing.Color.FromArgb(124, 80, 194);
            this.button2.Size = new System.Drawing.Size(102, 30);
            this.button2.TabIndex = 2;
            this.button2.Text = "Scan folder";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            this.txtbxDir.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.txtbxDir.BackColor = System.Drawing.Color.FromArgb(22, 17, 38);
            this.txtbxDir.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtbxDir.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtbxDir.ForeColor = System.Drawing.Color.FromArgb(222, 215, 236);
            this.txtbxDir.Location = new System.Drawing.Point(16, 31);
            this.txtbxDir.Name = "txtbxDir";
            this.txtbxDir.Size = new System.Drawing.Size(560, 23);
            this.txtbxDir.TabIndex = 1;
            this.txtbxDir.Text = "FNF Game Directory (ex: C:/Users/user/Documents/FNF)";
            this.txtbxDir.Enter += new System.EventHandler(this.txtbxDir_Enter);
            this.txtbxDir.Leave += new System.EventHandler(this.txtbxDir_Leave);
            this.lblPathTitle.AutoSize = true;
            this.lblPathTitle.Font = new System.Drawing.Font("Segoe UI Semibold", 8F);
            this.lblPathTitle.ForeColor = System.Drawing.Color.FromArgb(140, 128, 160);
            this.lblPathTitle.Location = new System.Drawing.Point(16, 10);
            this.lblPathTitle.Name = "lblPathTitle";
            this.lblPathTitle.Size = new System.Drawing.Size(97, 13);
            this.lblPathTitle.TabIndex = 0;
            this.lblPathTitle.Text = "GAME / CHART PATH";
            this.pnlTop.BackColor = System.Drawing.Color.FromArgb(18, 14, 31);
            this.pnlTop.Controls.Add(this.button1);
            this.pnlTop.Controls.Add(this.btnMinimize);
            this.pnlTop.Controls.Add(this.btnResetOffset);
            this.pnlTop.Controls.Add(this.label2);
            this.pnlTop.Controls.Add(this.label1);
            this.pnlTop.Controls.Add(this.lblVer);
            this.pnlTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlTop.Location = new System.Drawing.Point(0, 0);
            this.pnlTop.Name = "pnlTop";
            this.pnlTop.Size = new System.Drawing.Size(860, 56);
            this.pnlTop.TabIndex = 0;
            this.pnlTop.MouseDown += new System.Windows.Forms.MouseEventHandler(this.pnlTop_MouseDown);
            this.button1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.button1.CornerRadius = 7;
            this.button1.FlatAppearance.BorderSize = 0;
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.HoverColor = System.Drawing.Color.FromArgb(196, 65, 84);
            this.button1.Location = new System.Drawing.Point(814, 10);
            this.button1.Name = "button1";
            this.button1.NormalColor = System.Drawing.Color.FromArgb(70, 32, 48);
            this.button1.PressedColor = System.Drawing.Color.FromArgb(225, 72, 91);
            this.button1.Size = new System.Drawing.Size(34, 34);
            this.button1.TabIndex = 5;
            this.button1.Text = "×";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            this.btnMinimize.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnMinimize.CornerRadius = 7;
            this.btnMinimize.FlatAppearance.BorderSize = 0;
            this.btnMinimize.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMinimize.Font = new System.Drawing.Font("Segoe UI Semibold", 10F);
            this.btnMinimize.ForeColor = System.Drawing.Color.FromArgb(213, 205, 228);
            this.btnMinimize.HoverColor = System.Drawing.Color.FromArgb(60, 47, 84);
            this.btnMinimize.Location = new System.Drawing.Point(774, 10);
            this.btnMinimize.Name = "btnMinimize";
            this.btnMinimize.NormalColor = System.Drawing.Color.FromArgb(31, 24, 48);
            this.btnMinimize.PressedColor = System.Drawing.Color.FromArgb(79, 57, 112);
            this.btnMinimize.Size = new System.Drawing.Size(34, 34);
            this.btnMinimize.TabIndex = 4;
            this.btnMinimize.Text = "–";
            this.btnMinimize.UseVisualStyleBackColor = false;
            this.btnMinimize.Click += new System.EventHandler(this.btnMinimize_Click);
            this.btnResetOffset.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnResetOffset.CornerRadius = 7;
            this.btnResetOffset.FlatAppearance.BorderSize = 0;
            this.btnResetOffset.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnResetOffset.Font = new System.Drawing.Font("Segoe UI Semibold", 8F);
            this.btnResetOffset.ForeColor = System.Drawing.Color.FromArgb(211, 201, 228);
            this.btnResetOffset.HoverColor = System.Drawing.Color.FromArgb(64, 48, 91);
            this.btnResetOffset.Location = new System.Drawing.Point(665, 15);
            this.btnResetOffset.Name = "btnResetOffset";
            this.btnResetOffset.NormalColor = System.Drawing.Color.FromArgb(33, 26, 51);
            this.btnResetOffset.PressedColor = System.Drawing.Color.FromArgb(87, 61, 128);
            this.btnResetOffset.Size = new System.Drawing.Size(95, 26);
            this.btnResetOffset.TabIndex = 3;
            this.btnResetOffset.Text = "Reset offset";
            this.btnResetOffset.UseVisualStyleBackColor = false;
            this.btnResetOffset.Click += new System.EventHandler(this.btnResetOffset_Click);
            this.label2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 9F);
            this.label2.ForeColor = System.Drawing.Color.FromArgb(181, 163, 217);
            this.label2.Location = new System.Drawing.Point(535, 28);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(118, 20);
            this.label2.TabIndex = 2;
            this.label2.Text = "Offset: 25";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.label1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label1.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.label1.ForeColor = System.Drawing.Color.FromArgb(142, 129, 162);
            this.label1.Location = new System.Drawing.Point(490, 8);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(163, 18);
            this.label1.TabIndex = 1;
            this.label1.Text = "Time: 00:00:000";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lblVer.AutoSize = true;
            this.lblVer.Font = new System.Drawing.Font("Segoe UI Semibold", 14F);
            this.lblVer.ForeColor = System.Drawing.Color.FromArgb(244, 240, 250);
            this.lblVer.Location = new System.Drawing.Point(20, 15);
            this.lblVer.Name = "lblVer";
            this.lblVer.Size = new System.Drawing.Size(73, 25);
            this.lblVer.TabIndex = 0;
            this.lblVer.Text = "FNFBot";
            this.lblVer.MouseDown += new System.Windows.Forms.MouseEventHandler(this.pnlTop_MouseDown);
            this.navAnimationTimer.Interval = 12;
            this.navAnimationTimer.Tick += new System.EventHandler(this.navAnimationTimer_Tick);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(13, 10, 23);
            this.ClientSize = new System.Drawing.Size(1040, 680);
            this.Controls.Add(this.pnlMain);
            this.Controls.Add(this.pnlSidebar);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(900, 620);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FNFBot";
            this.Resize += new System.EventHandler(this.Form1_Resize);
            this.pnlSidebar.ResumeLayout(false);
            this.pnlSidebar.PerformLayout();
            this.pnlMain.ResumeLayout(false);
            this.pnlPageHost.ResumeLayout(false);
            this.pnlKeybindPage.ResumeLayout(false);
            this.pnlKeybindPage.PerformLayout();
            this.pnlLaneBindings.ResumeLayout(false);
            this.pnlLaneBindings.PerformLayout();
            this.pnlControlBindings.ResumeLayout(false);
            this.pnlControlBindings.PerformLayout();
            this.pnlDashboardPage.ResumeLayout(false);
            this.pnlLibraryCard.ResumeLayout(false);
            this.pnlLibraryCard.PerformLayout();
            this.pnlConsoleCard.ResumeLayout(false);
            this.pnlConsoleCard.PerformLayout();
            this.pnlPreviewCard.ResumeLayout(false);
            this.pnlPreviewCard.PerformLayout();
            this.pnlPathCard.ResumeLayout(false);
            this.pnlPathCard.PerformLayout();
            this.pnlTop.ResumeLayout(false);
            this.pnlTop.PerformLayout();
            this.ResumeLayout(false);
        }

        private System.Windows.Forms.Panel pnlSidebar;
        private System.Windows.Forms.Label lblSidebarFooter;
        private System.Windows.Forms.Panel navIndicator;
        private FNFBot20.AnimatedButton navKeybinds;
        private FNFBot20.AnimatedButton navDashboard;
        private System.Windows.Forms.Label lblBrandSubtitle;
        private System.Windows.Forms.Panel pnlLogo;
        private System.Windows.Forms.Panel pnlMain;
        private System.Windows.Forms.Panel pnlPageHost;
        private FNFBot20.DoubleBufferedPanel pnlKeybindPage;
        private FNFBot20.RoundedPanel pnlLaneBindings;
        private System.Windows.Forms.FlowLayoutPanel flpLaneKeys;
        private FNFBot20.AnimatedButton btnResetAllLaneKeys;
        private FNFBot20.AnimatedButton btnResetLaneKeys;
        private System.Windows.Forms.ComboBox cmbLaneCount;
        private System.Windows.Forms.Label lblDetectedLayout;
        private System.Windows.Forms.Label lblLaneProfile;
        private FNFBot20.RoundedPanel pnlControlBindings;
        private FNFBot20.AnimatedButton btnResetShortcuts;
        private FNFBot20.AnimatedButton btnBindOffsetDown;
        private FNFBot20.AnimatedButton btnBindOffsetUp;
        private FNFBot20.AnimatedButton btnBindPlay;
        private System.Windows.Forms.Label lblOffsetDownKey;
        private System.Windows.Forms.Label lblOffsetUpKey;
        private System.Windows.Forms.Label lblPlayKey;
        private System.Windows.Forms.Label lblOffsetDownName;
        private System.Windows.Forms.Label lblOffsetUpName;
        private System.Windows.Forms.Label lblPlayName;
        private System.Windows.Forms.Label lblControlBindingsTitle;
        private System.Windows.Forms.Label lblKeybindSubtitle;
        private System.Windows.Forms.Label lblKeybindTitle;
        private FNFBot20.DoubleBufferedPanel pnlDashboardPage;
        private FNFBot20.RoundedPanel pnlLibraryCard;
        private System.Windows.Forms.TreeView treSngSelect;
        private System.Windows.Forms.Label lblLibraryTitle;
        private FNFBot20.RoundedPanel pnlConsoleCard;
        private System.Windows.Forms.RichTextBox rchConsole;
        private System.Windows.Forms.Label lblConsoleTitle;
        private FNFBot20.RoundedPanel pnlPreviewCard;
        private System.Windows.Forms.Panel pnlPlayField;
        private System.Windows.Forms.CheckBox checkBox1;
        private System.Windows.Forms.Label lblPreviewTitle;
        private FNFBot20.RoundedPanel pnlPathCard;
        private FNFBot20.AnimatedButton btnManual;
        private FNFBot20.AnimatedButton button2;
        private System.Windows.Forms.TextBox txtbxDir;
        private System.Windows.Forms.Label lblPathTitle;
        private System.Windows.Forms.Panel pnlTop;
        private FNFBot20.AnimatedButton button1;
        private FNFBot20.AnimatedButton btnMinimize;
        private FNFBot20.AnimatedButton btnResetOffset;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label lblVer;
        private System.Windows.Forms.Timer navAnimationTimer;
    }
}
